name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        # PyPI user
        user: ${{ secrets.PYPI_USERNAME }}
        # Password for your PyPI user or an access token
        password: ${{ secrets.PYPI_PASSWORD }}
        # The repository URL to use
        #repository_url: # optional
        # The target directory for distribution
        #packages_dir: # optional, default is dist
